#!/bin/sh
set -e
set -x

cd assets/js-external
wget https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css
wget https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
wget https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js
wget https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js
wget https://raw.githubusercontent.com/jhvanderschee/hugocodex/main/static/js/carousel.js
wget https://raw.githubusercontent.com/jhvanderschee/hugocodex/main/static/css/carousel.css